name: amazon_cognito_identity_dart
version: 0.0.18
author: Jon Saw <jon.saw@gmail.com>
homepage: https://github.com/jonsaw/amazon-cognito-identity-dart/tree/master
description: Unofficial Amazon Cognito Identity Provider Dart SDK,
  to easily add user sign-up and sign-in to your mobile and web apps
  with AWS Cloud Services.

dependencies:
  crypto: ^2.0.2+1
  http: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^0.12.35

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
